<a href="https://colab.research.google.com/github/Adwe100/data_science_bootcamp/blob/main/01_wprowadzenie/01intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__


'1.21.6'

In [3]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
A[-1]

19

In [4]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[3,:]

array([15, 16, 17, 18, 19])

In [ ]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [6]:
A[1,2]=20
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 20,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
for row in A:
  print(row[0])

0
5
10
15


In [8]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
20
8
9
10
11
12
13
14
15
16
17
18
19


In [9]:
A.shape

(4, 5)

In [13]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 20,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 20, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [15]:
A = np.arange(start=-10,stop=10,step=0.5)

In [18]:
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [19]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [20]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [21]:
np.bitwise_and(A>-5,A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [22]:
np.bitwise_or(A<-5,A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])