<a href="https://colab.research.google.com/github/Adwe100/data_science_bootcamp/blob/main/01_wprowadzenie/algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.21.6'

In [6]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [7]:
np.linalg.norm(v1)

4.123105625617661

In [8]:
v2= np.array([-10,10,13])
v2

array([-10,  10,  13])

In [9]:
np.linalg.norm(v2)

19.209372712298546

In [10]:
p = np.array([3,0])
q = np.array([0,4])
np.linalg.norm(p-q)

5.0

In [13]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])
np.linalg.norm(p-q)

5.0990195135927845

In [16]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [17]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [18]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [20]:
Z = np.dot(X,Y)
print(Z)

[[13  9 -4]
 [ 6  2 -1]]


In [21]:
A = np.array([[2, 4], [-1, 3]])
A

array([[ 2,  4],
       [-1,  3]])

In [23]:
round(np.linalg.det(A))

10

In [24]:
np.trace(A)

5

In [25]:
np.eye(6,dtype="int")

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [28]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [32]:
from numpy.core.memmap import dtype
np.set_printoptions(precision=4,suppress=True)
Z = np.dot(A,B)

In [35]:
A = np.array([[2, 4], [1, -1]])
print(A,"\n")
B = np.array([[10], [-1]])
print(B)

[[ 2  4]
 [ 1 -1]] 

[[10]
 [-1]]


In [42]:
A_innv = np.linalg.inv(A)
X = np.dot(A_innv,B)
X

array([[1.],
       [2.]])