<a href="https://colab.research.google.com/github/Adwe100/data_science_bootcamp/blob/main/01_wprowadzenie/statystyka.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.21.6'

In [3]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [7]:
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [9]:
np.min(price,axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [10]:
np.median(price)

12.6

In [11]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])